### ISSUE TITLE
二维码登陆报错

### ISSUE THREAD

**Issue by CHKZL** [LeoChen98/BiliAccount#21]
调用ByQRCode.LoginByQrCode()会出现“Unable to cast object of type 'System.Int64' to type 'System.Int32”的提示

在新建的空白core3.1控制台程序中也是如此
![H `J(9FI%U %7`$ZES~A}PO](https://user-images.githubusercontent.com/20613600/80871720-744d3000-8ce0-11ea-8945-bceb50ab27a5.png)

**Comment by LeoChen98** [comment]
使用的版本号？最新版的我这里测试没有出现任何错误。。。

**Comment by CHKZL** [comment]
通过nuget安装的2.3.4.18
在新新建的.net framework 4.7.2控制台项目和.net core3.1控制台中使用同样的代码测试，确实只有core会出现这个错误，在.net4.7.2中正常运行

![image](https://user-images.githubusercontent.com/20613600/80909007-3c350400-8d57-11ea-95cc-c848bf71f31e.png)

**Comment by LeoChen98** [comment]
已定位错误为core中转换数字为long而非int，已在`2.3.5.19`解决。
