### ISSUE TITLE
【寻求帮助】Bilibili账号登录问题

### ISSUE THREAD

**Issue by withsalt** [LeoChen98/BiliAccount#6]
老哥你好，之前搞了一个B站直播推流工具。
个人仓库：https://github.com/withsalt/BilibiliLiveTools
但是最近Bilibili更新了登录接口，导致目前工具无法登录和刷新Token（无法登录的问题已经解决）。由于最初的登录API不是我本人写的，Fork的其它开源项目，所以对Bilibili登录认证机制不熟悉。所以希望能得到老哥的帮助，解决Bilibili登录认证这块的问题。
十分感谢！！

**Comment by LeoChen98** [comment]
B站的登录主要有两种方式，一种是扫码登录，通过刷新二维码状态接口获取登录cookies；另一种是OAuth2+SSO获取cookies，这个库里都实现了的，你可以直接用。
