### ISSUE TITLE
关于增加用于生成登陆二维码的字符串获取

### ISSUE THREAD

**Issue by CHKZL** [LeoChen98/BiliAccount#94]
在.NET5/6中在除了Windows平台外的linux和MacOS平台上，使用现有的二维码登陆方法需要调用System.Drawing.Common
然而common需要依赖libgdiplus，而libgdiplus还需要添加mono库\源，对于纯控制台程序来说不太合适。

是否能把用于生成二维码的`http://XXXXXXXXXXX/qrcode/h5/login?oauthKey=xxxxx`字段给暴露出来，方便直接使用控制台绘制二维码进行操作？

**Comment by LeoChen98** [comment]
在做了，代码实现了，然而生成的时候一堆莫名错误，回头再看看

**Comment by LeoChen98** [comment]
done.
