### ISSUE TITLE
密码登录失败：NeedSafeVerify

### ISSUE THREAD

**Issue by withsalt** [LeoChen98/BiliAccount#96]
你好，使用你的库密码登录时提示NeedSafeVerify。密码登录现在不能使用了吗？  
版本：2.5.5.27  

[![7No9xK.md.jpg](https://s4.ax1x.com/2022/01/16/7No9xK.md.jpg)](https://imgtu.com/i/7No9xK)

**Comment by LeoChen98** [comment]
现在情况是接口改了，然后还换了appkey和appsecret，一时半会是处理不了。

**Comment by LeoChen98** [comment]
你也可以强行按照NeedTelVerify的处理方案，用Geetest类下面的方法过验证试试。

**Comment by withsalt** [comment]
感谢解答。
